version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    restart: always
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - PORT=3000
      - DB_HOST=${DB_HOST:-localhost}
      - DB_PORT=${DB_PORT:-5432}
      - DB_USERNAME=${DB_USERNAME:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_NAME=${DB_NAME:-backend_sw}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - JWT_SECRET=${JWT_SECRET:-secreto_por_defecto}
      - JWT_EXPIRATION_TIME=${JWT_EXPIRATION_TIME:-1d}
    volumes:
      - ./.env:/app/.env
    network_mode: host 